"""fix passwd columns

Revision ID: 9ab49400951a
Revises: 13087ecbba3c
Create Date: 2026-03-04 03:31:01.829664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ab49400951a"
down_revision: Union[str, Sequence[str], None] = "13087ecbba3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
