"""added hotel IP to booking model

Revision ID: 082de54f0ba1
Revises: 60bca803d23b
Create Date: 2026-03-27 19:35:46.107942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "082de54f0ba1"
down_revision: Union[str, Sequence[str], None] = "60bca803d23b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("hotel_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "bookings", "hotels", ["hotel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.drop_column("bookings", "hotel_id")
    # ### end Alembic commands ###
